### ISSUE TITLE
Unable to authorize tidal account

### ISSUE THREAD

**Issue by chandranorth** [tehkillerbee/mopidy-tidal#102]
This just happened recently, and it may be due to a change on Tidal's end.

I just recently noticed that my mopidy instance was stuck because it was waiting for tidal authorization:  here is representative output on querying the status of mopidy

sudo systemctl status mopidy
● mopidy.service - Mopidy music server
     Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-04-11 19:18:15 CDT; 4s ago
    Process: 4237 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 4239 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
   Main PID: 4240 (mopidy)
      Tasks: 12 (limit: 1595)
        CPU: 2.728s
     CGroup: /system.slice/mopidy.service
             └─4240 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: TidalBackend, FileBackend, M3UBackend, StreamBackend, TuneInBackend, SomaFMBackend, Local>
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Connecting to TIDAL.. Quality = LOSSLESS
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Connecting to TIDAL.. using default client id & client secret from python-tidal
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Loading OAuth session from /var/lib/mopidy/tidal/tidal-oauth.json...
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink locat>
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [SomaFMBackend-8] mopidy_somafm.somafm Loaded 39 SomaFM channels
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Could not load OAuth session from /var/lib/mopidy/tidal/tidal-oauth.json: 'picture'
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Creating new OAuth session...
Apr 11 19:18:18 mopidy mopidy[4240]: INFO     [TidalBackend-3] mopidy_tidal.backend Visit link.tidal.com/NSBVI to log in, the code will expire in 300 seconds

After I go to the link and authorize, which seems to be successful, mopidy-tidal does not start.  Looking at the status of mopidy again, I see the error that the Tidal backend did not start:

pi@mopidy:~ $ sudo systemctl status mopidy
● mopidy.service - Mopidy music server
     Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-04-11 19:18:15 CDT; 27s ago
    Process: 4237 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 4239 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
   Main PID: 4240 (mopidy)
      Tasks: 15 (limit: 1595)
        CPU: 3.252s
     CGroup: /system.slice/mopidy.service
             └─4240 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Apr 11 19:18:38 mopidy mopidy[4240]:     self.picture_id = json_obj['picture']
Apr 11 19:18:38 mopidy mopidy[4240]: KeyError: 'picture'
Apr 11 19:18:38 mopidy mopidy[4240]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:a1657973-809e-40a0-a64d-6bca66361d07) stopped before handling the message
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: IrisFrontend, HttpFrontend, MpdFrontend
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [IrisFrontend-11] mopidy_iris.core Starting Iris 3.66.0
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [HttpFrontend-13] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:127.0.0.1]:6600
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Apr 11 19:18:38 mopidy mopidy[4240]: WARNING  [HttpServer] mopidy.http.handlers HTTP Cross-Site Request Forgery protection is disabled
pi@mopidy:~ $ journalctl -u mopidy | tail -10
Apr 11 19:18:38 mopidy mopidy[4240]: KeyError: 'picture'
Apr 11 19:18:38 mopidy mopidy[4240]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:a1657973-809e-40a0-a64d-6bca66361d07) stopped before handling the message
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: IrisFrontend, HttpFrontend, MpdFrontend
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [IrisFrontend-11] mopidy_iris.core Starting Iris 3.66.0
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [HttpFrontend-13] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:127.0.0.1]:6600
Apr 11 19:18:38 mopidy mopidy[4240]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Apr 11 19:18:38 mopidy mopidy[4240]: WARNING  [HttpServer] mopidy.http.handlers HTTP Cross-Site Request Forgery protection is disabled
Apr 11 19:18:47 mopidy mopidy[4240]: INFO     [MpdSession-15] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:36708

It seems the error is that the key "picture" is not in the json file /var/lib/mopidy/tidal/tidal-oauth.json.  The only keys in the json file are "token_type", "session_id", "access_token" and "refresh_token".  Has anyone come across this problem before, and if so, is there a solution?  The setup was working without any problems earlier.

Thanks in advance.

chandranorth

**Comment by tehkillerbee** [comment]
Closing as duplicate issue

**Comment by chandranorth** [comment]
Thanks!
     On Thursday, April 13, 2023, 06:00:44 AM CDT, Johannes L ***@***.***> wrote:  
 
 


@chandranorth This is a known issue, please refer to the issue mentioned here for a solution #97

If you install latest mopidy-tidal from master, you should not have any issues. The release on PyPi still uses the old tidalapi from Tamland, and it has not currently been fixed.
