### ISSUE TITLE
Reorganize README

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#115]
Due to the size of the README, it is probably time to split it into multiple sections.

Eg. 

- README (short overview on how to get started)

- Developer notes, changelog, contributors etc. should be moved to separate sections and possibly a 'docs' subdir.

**Comment by 2e0byo** [comment]
Or we could have a really small static site?  something like [this](https://2e0byo.github.io/gallica-autobib/) (shameless plug for one of my own slightly abandoned projects, the site is built out of [a single dir of md files](https://github.com/2e0byo/gallica-autobib/tree/master/docs)).  Or even readthedocs, although I'm not a *massive* fan of sphinx in small projects: I'd rather just read the source.

**Comment by tehkillerbee** [comment]
@2e0byo Also a good idea. Ideally, it should be easy to maintain so if can be generated directly from md, that is a good solution.

**Comment by tehkillerbee** [comment]
For now, I have made some smaller changes to the docs.
