### ISSUE TITLE
Add support for HI_RES LOSSLESS quality

### ISSUE THREAD

**Issue by 9acca9** [tehkillerbee/mopidy-tidal#121]
would you update so we all can hear the best quality? pleeeeeeeaaaaaaseeeeee.

I think that before it was not possible because of MQA but it seems that now Tidal will use just a beautiful FLAC file:
https://www.reddit.com/r/TIdaL/comments/14nbps7/hi_res_lets_go_got_the_tidal_eap_and_hi_res_flac/?utm_source=share&utm_medium=web2x&context=3

https://www.digitaltrends.com/home-theater/tidal-adds-hi-res-lossless-flac/

Thanks!

**Comment by tehkillerbee** [comment]
Thanks for the heads-up - very exciting news.

I will need to test further to see how support can be added - most likely in tidalapi.

**Comment by JoshMock** [comment]
I've played with lossless in `tidalapi` and it seems to already be downloading a FLAC file. :+1:

**Comment by tehkillerbee** [comment]
@vaosilva Yep, I am working on adding support as we speak. There was a holiday, that came in the way ;)
