### ISSUE TITLE
Mopidy-Tidal don't work

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#126]
Hi ! 
I have been experiencing for a few hours the non-functioning of Mopidy-Tidal which is unable to authenticate

thon3.7/dist-packages/tidalapi/request.py", line 118, in map_request
    return self.map_json(json_obj, parse=parse)
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/request.py", line 125, in map_json
    return parse(json_obj)
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 65, in parse
    return user.parse(json_obj)
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 114, in parse
    self.gender = json_obj["gender"]
KeyError: 'gender'
ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:2fd246a9-87de-4cad-a22e-de92a3332e5d) stopped before handling the message
INFO     [MainThread] mopidy.commands Starting Mopidy core
INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:127.0.0.1]:6600
INFO     [HttpFrontend-8] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680

can you help me ?
many thanks !

**Comment by fmarzocca** [comment]
see [here](https://github.com/tehkillerbee/mopidy-tidal/issues/122#issuecomment-1626901893)

**Comment by chicco64** [comment]
many thanks !!!!

**Comment by tehkillerbee** [comment]
PyPi package for tidalapi has now been updated to the latest release. Please make sure you upgrade to latest v0.7.2 release. Marking this issue as fixed.
