### ISSUE TITLE
Add support for "free" subscription. 

### ISSUE THREAD

**Issue by curiousercreative** [tehkillerbee/mopidy-tidal#128]
I just created a free account on Tidal hoping this would work. I am indeed able to search and browse the Tidal catalog, but I get errors logged like this when I attempt to add tracks to play queue:
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/tracks/116125921/urlpostpaywall?sessionId=xxxxxxxxx&countryCode=US&limit=1000&urlusagemode=STREAM&audioquality=HIGH&assetpresentation=FULL

Attempting to replicate the request in Postman, I can see an error message:
> Requested quality is not allowed in user's subscription

Should we expect that the API is restricted to paying subscribers or should it work with a free account as well? The documentation around the "quality" setting suggests that Hi-Fi (paid) subscription is only necessary for LOSSLESS quality.

FWIW, I've verified my email address, I'm able to play music on the Tidal web player and I'm able to auth mopidy and browse/search the catalog.

**Comment by tehkillerbee** [comment]
I've never tested with free subscription (I didn't know it exists until you mentioned it). But I suspect that you need to use a different quality setting that matches the free subscription.

**Comment by tehkillerbee** [comment]
Yes, I'm interested in what you find out as this would make both mopidy-tidal and tidalapi even more useful. 

Unfortunately, tidalapi has no way of listing the available qualities for a session, so it would require some reverse engineering...

**Comment by curiousercreative** [comment]
I wouldn't be surprised if the error message is a bit misleading and the free tier is not allowed any quality.

**Comment by tehkillerbee** [comment]
The quality setting corresponds to the subscription, although it is also possible to configure a "high/lossless/Hifi" subscription with a low(er) quality. 

So I would expect a quality setting corresponding to the free subscription.

**Comment by curiousercreative** [comment]
The web player UI has two quality options and they map as expected:
- "Normal" => "LOW"
- "High" => "HIGH"

I deduce the above based on the first request made for a track:
- "Normal":  https://listen.tidal.com/v1/tracks/204275364/playbackinfopostpaywall/v4?audioquality=LOW&playbackmode=STREAM&assetpresentation=FULL&streamingsessionid=737e1bc3-8c22-4248-a7c2-b69851bb6e43
- "High": https://listen.tidal.com/v1/tracks/116125907/playbackinfopostpaywall/v4?audioquality=HIGH&playbackmode=STREAM&assetpresentation=FULL&streamingsessionid=fac2a58b-383d-45e6-a4bc-f8db83c6935a

I gathered the above from the Firefox native developer tools network tab from [this web player page](https://listen.tidal.com/album/116125894).

**Comment by curiousercreative** [comment]
Here's interesting response data from a subscription endpoint:

```json
{
  "startDate": "2023-08-01T17:30:40.615+0000",
  "validUntil": "2023-08-31T17:30:40.615+0000",
  "status": "ACTIVE",
  "subscription": {
    "type": "INTRO",
    "offlineGracePeriod": 0
  },
  "highestSoundQuality": "HIGH",
  "premiumAccess": false,
  "canGetTrial": true,
  "paymentType": "NONE",
  "paymentOverdue": false
}
```

**Comment by curiousercreative** [comment]
Seems the free tier has been sing since Nov 2021: https://duckduckgo.com/?q=tidal+free+tier

**Comment by curiousercreative** [comment]
It seems the 401 response with message "Requested quality is not allowed in user's subscription" is returned in a variety of obviously bad request scenarios which leads me to believe it may not actually be the issue. If I take a request that is seemingly valid and remove the auth header, I still get the same response.

I get a 401 with message "Asset is not ready for playback" when I omit the "audioQuality", "assetpresentation", or "urlusagemode" params.

I get a 401 "Missing sessionId" when "sessionId" param is omitted.

I get a 404 "Resource not found" when supplying an invalid "audioQuality"

**Comment by curiousercreative** [comment]
Here's a little more of what I see in mopidy logs

```
INFO     2023-08-02 12:11:07,226 [7:TidalBackend-3] mopidy_tidal.library
 Lookup uris 'tidal:album:116125894'
INFO     2023-08-02 12:11:07,291 [7:TidalBackend-3] mopidy_tidal.library
 Returning 18 tracks
INFO     2023-08-02 12:11:07,317 [7:TidalBackend-3] mopidy_tidal.library
 Searching Tidal for images for ['tidal:album:116125894']
INFO     2023-08-02 12:11:16,686 [7:TidalBackend-3] mopidy_tidal.library
 Lookup uris 'tidal:track:3557299:116125894:116125895'
INFO     2023-08-02 12:11:16,691 [7:TidalBackend-3] mopidy_tidal.library
 Returning 1 tracks
INFO     2023-08-02 12:11:16,775 [7:TidalBackend-3] mopidy_tidal.playback
 TIDAL uri: tidal:track:3557299:116125894:116125895
ERROR    2023-08-02 12:11:16,950 [7:Core-9] mopidy.core.playback
 TidalBackend backend caused an exception.
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 352, in _change
   if not backend.playback.change_track(pending_tl_track.track).get():
 File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
   _compat.reraise(*self._data['exc_info'])
 File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
   raise value
 File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
   response = self._handle_receive(envelope.message)
 File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
   return callee(*message.args, **message.kwargs)
 File "/usr/lib/python3/dist-packages/mopidy/backend.py", line 331, in change_track
   uri = self.translate_uri(track.uri)
 File "/var/lib/mopidy/.local/lib/python3.9/site-packages/mopidy_tidal/playback.py", line 17, in translate_uri
   newurl = session.track(track_id).get_url()
 File "/var/lib/mopidy/.local/lib/python3.9/site-packages/tidalapi/media.py", line 199, in get_url
   request = self.requests.request(
 File "/var/lib/mopidy/.local/lib/python3.9/site-packages/tidalapi/request.py", line 98, in request
   request.raise_for_status()
 File "/var/lib/mopidy/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/tracks/116125895/urlpostpaywall?sessionId=6d827b2c-d89e-4659-b4b0-93d22b251dff&countryCode=US&limit=1000&urlusagemode=STREAM&audioquality=HIGH&assetpresentation=FULL
WARNING  2023-08-02 12:11:16,955 [7:Core-9] mopidy.core.tracklist
 Track is not playable: tidal:track:3557299:116125894:116125895
```

**Comment by curiousercreative** [comment]
Sending Postman requests (simulating the mopidy stream) pauses my Android app or Web player if there's a song playing there, so it's properly authorized it seems.

**Comment by tehkillerbee** [comment]
Hmm.. I suspected that the free subscription does not allow streaming from other clients, but it seems this is not the case when you can use both web and android.

I think it is a good idea to add the issue to the tidalapi project too, as the feature must be added to tidalapi before we can add it to mopidy-tidal.

https://github.com/tamland/python-tidal

**Comment by tehkillerbee** [comment]
Closed as per the discussion in python-tidal
