### ISSUE TITLE
what about the integration with Iris?

### ISSUE THREAD

**Issue by 9acca9** [tehkillerbee/mopidy-tidal#129]
I mean, with https://github.com/jaedb/Iris

mopidy-tidal works pretty well with iris, except for a few things. Like the pictures in the search (you cant see any picture of what you search, no artist, no album).
Thanks.

Ps: i also say this to iris github creator (time ago)

**Comment by tehkillerbee** [comment]
@9acca9 This is already an existing issue. Please refer to it if there are specific things we should add.

https://github.com/tehkillerbee/mopidy-tidal/issues/61
