### ISSUE TITLE
Some mixes missing (My New Arrivals)

### ISSUE THREAD

**Issue by mkozjak** [tehkillerbee/mopidy-tidal#130]
Hello,

First of all, thanks for the great work on this plugin!

Are there any reasons I'm not having the "My New Arrivals" mix in my ncmpcpp browser under Tidal/Mixes?

<img width="800" alt="image" src="https://github.com/tehkillerbee/mopidy-tidal/assets/3506172/7c27f664-3cff-4a22-b859-c282d8517723">

Also, is there a way to get the "For you" section from Tidal? Usually appears on the first line in Home on the Tidal browser.

**Comment by tehkillerbee** [comment]
> Are there any reasons I'm not having the "My New Arrivals" mix in my ncmpcpp browser under Tidal/Mixes?

> Also, is there a way to get the "For you" section from Tidal? 

You need to add them first, i.e. click the heart/add button. Otherwise, they will not show up in your Mixes.

Other than adding them to your mixes, there appears to be no other way they can be fetched through tidalapi.

**Comment by mkozjak** [comment]
Ok, so I added them to my collection but it didn't end up in Mixes.
TBH I can't find it anywhere in my tidal collection when I try looking for it at listen.tidal.com 💩.
<img width="789" alt="image" src="https://github.com/tehkillerbee/mopidy-tidal/assets/3506172/beefc6c9-e981-470d-9722-1899bec3c105">

<img width="771" alt="image" src="https://github.com/tehkillerbee/mopidy-tidal/assets/3506172/e99f6ea4-9077-4ca6-9b23-01bc16c8557f">

**Comment by tehkillerbee** [comment]
This feature is added to v0.3.4. You should be able to find the mixes/playlists on either the "explore" or "for you" page.
