### ISSUE TITLE
Tests are currently broken due to changes in tidalapi

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#133]
See this discussion for more details:
https://github.com/tehkillerbee/mopidy-tidal/discussions/132

PRs are still welcome but be aware that somee tests currently fail with slightly confusing error messages.

**Comment by 9acca9** [comment]
HI, thanks for all your work and time, i can help, if this is automated in some way, i dont know how to code, etc. (just copy paste / mix / ask / mix / change a little / paste)
But again if i can help here i am, i could try.

**Comment by tehkillerbee** [comment]
@9acca9 Thanks so much for offering to help testing. 

Tests should (eventually) be fully automated. Until then, just being a user of mopidy-tidal and reporting any issues that you experience is greatly appreciated. Feedback when used together with other plugins (Iris etc.) is also very appreciated as it can help us improve mopidy-tidal further.

**Comment by 9acca9** [comment]
hi.
What about:
`tidal/quality must be one of 'LOSSLESS', 'HIGH', 'LOW', not HI_RES_LOSSLESS.`

?
Thanks.

**Comment by tehkillerbee** [comment]
Are you talking about a failed test or a different error?

If it is the latter, you should make sure to update tidalapi.
