### ISSUE TITLE
Incorrect tests for nonexistent objects

### ISSUE THREAD

**Issue by 2e0byo** [tehkillerbee/mopidy-tidal#137]
See e.g. https://github.com/tehkillerbee/mopidy-tidal/blob/33b41e1f15a425fd983c172bacd48147a30f1fe2/mopidy_tidal/library.py#L395

This check is incorrect as tidalapi never returns anything falsy, but *does* raise an exception if an invalid album is accessed.

**Comment by 2e0byo** [comment]
The recent typing work will actually catch these bugs, so that's good

**Comment by tehkillerbee** [comment]
Fixed in https://github.com/tehkillerbee/mopidy-tidal/pull/151
