### ISSUE TITLE
Setting HI_RES_LOSSLESS returns error

### ISSUE THREAD

**Issue by 9acca9** [tehkillerbee/mopidy-tidal#139]
Im posting here the error.
Is not a test, just using the last v0.3.4 installed from pypi and  tidalapi 0.7.3

Trying to set to HI_RES_LOSSLESS

`tidal/quality must be one of 'LOSSLESS', 'HIGH', 'LOW', not HI_RES_LOSSLESS.`

Maybe this is not working yet?

Thanks.

**Comment by tehkillerbee** [comment]
@9acca9  I just verified again on my dev PC and everything works as expected:
```
...
[TidalBackend-6 (_actor_loop)] mopidy_tidal.backend Connecting to TIDAL... Quality = HI_RES_LOSSLESS
...
```

Can you try reinstalling mopidy-tidal and tidalapi, i.e.
```
sudo pip3 uninstall mopidy-tidal
sudo pip3 install mopidy-tidal --no-cache-dir --force
```

Note: The above steps depends on your python configuration so perhaps there are some remains of your old tidal version.
We should probably print the installed version to the log.. Adding an issue for that.

**Comment by 9acca9** [comment]
Thanks.
is working!
