### ISSUE TITLE
PKCE

### ISSUE THREAD

**Issue by fmarzocca** [tehkillerbee/mopidy-tidal#155]
Do you have a sort of how-to to use the new PKCE authentication for HiRes quality?

**Comment by tehkillerbee** [comment]
Yes, it's all outlined in the readme. You'll need to set auth_mode and the port to use for the webserver used for the authentication.
```
auth_method = PKCE
login_server_port = 8989
```
For the login procedure, this is described here:
https://github.com/tehkillerbee/mopidy-tidal?tab=readme-ov-file#pkce-flow

**Comment by fmarzocca** [comment]
Will try, thanks!

**Comment by fmarzocca** [comment]
Upon restart, I got this in my log:
```

2024-03-02 14:54:03,852 INFO [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: Quality: HI_RES_LOSSLESS
2024-03-02 14:54:03,864 INFO [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: Authentication: PKCE
2024-03-02 14:54:03,870 WARNING [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: AUTO login implies lazy connection, setting lazy=True.
2024-03-02 14:54:03,872 INFO [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: Login method: AUTO
2024-03-02 14:54:03,885 INFO [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: Using default client id & client secret from python-tidal
```

**Comment by tehkillerbee** [comment]
> I am running mopidy on an headless server.

Yes, I do the same. 

Yes, this is not clear from the instructions. If you are using a headless server, you should replace local host with the IP address of your device. Eg. 192.168.0.10:8989

**Comment by fmarzocca** [comment]
> If you are using a headless server, you should replace local host with the IP address of your device. Eg. 192.168.0.10:8989.

not working anyway...

**Comment by fmarzocca** [comment]
I finally got it!
The authentication procedure is quite tricky...

**Comment by tehkillerbee** [comment]
What IP address are you using to access your server?

Since you are using lazy browsing enabled , you'd need to browse the tidal folder structure before the login server is triggered.

**Comment by fmarzocca** [comment]
I didn't read the **General login tips**.
Maybe just add a note in the instructions: **Please read here**

**Comment by fmarzocca** [comment]
I did not have any "lazy" setting so I assumed it was false (default). But the logs reported:

`2024-03-02 14:54:03,870 WARNING [2113:TidalBackend-3 (_actor_loop)] mopidy_tidal.backend: AUTO login implies lazy connection, setting lazy=True`

**Comment by tehkillerbee** [comment]
Added more details to documentation in v0.3.6
