### ISSUE TITLE
Iris: Missing cover in the bottom left, "Now playing", "Kiosk" mode

### ISSUE THREAD

**Issue by GioF71** [tehkillerbee/mopidy-tidal#157]
Hello, thank you again for the incredible work.
Small issue: it appears that the cover image is not correctly displayed in the bottom left of the window.
See:

![image](https://github.com/tehkillerbee/mopidy-tidal/assets/5603160/4b74eba3-8c67-486f-a463-62a3fb6716db)

Also clicking there, in the kiosk mode, the cover is missing.

Edit: apparently I cannot tell left from right

**Comment by tehkillerbee** [comment]
I did notice that too. I think it might be a quirk in Iris, but I have not yet tested it. It also looks like the album art is missing. Perhaps you need to clear the tidal cache to make sure the images are reloaded.

![image](https://github.com/tehkillerbee/mopidy-tidal/assets/815886/58350139-91df-4420-8792-ef0e17962f95)

**Comment by GioF71** [comment]
Hello, I tried clearing the cache, but this did not solve the issue unfortunately

**Comment by fmarzocca** [comment]
I'm not using Iris, but my artworks are all visible.

**Comment by tehkillerbee** [comment]
Yes, I think this is largely an iris problem. Not sure if the maintainer is aware however, there are many small issues when using iris paired with mopidy-tidal. I think it works better with Spotify. 

What frontend do you currently use?

**Comment by fmarzocca** [comment]
I use NodeRed as the frontend, managed via mqtt with my [extension](https://github.com/fmarzocca/Mopiqtt).

<img width="341" alt="Screenshot 2024-03-02 alle 16 32 25" src="https://github.com/tehkillerbee/mopidy-tidal/assets/8530030/1db50ea1-c88b-41dd-8e14-764fc9f6c953">

**Comment by fmarzocca** [comment]
I have to correct myself: artworks are there is I select a Radio Stream. No more there is I select a Tidal playlist....

**Comment by fmarzocca** [comment]
Try these 2 examples:

Get a radio stream image:
`curl -d '{"jsonrpc":"2.0","id":1,"method":"core.library.get_images","params":{"uris":["tunein:station:s74986"]}}' -H 'Content-Type: application/json' http://localhost:6680/mopidy/rpc`
Result:
`{"jsonrpc": "2.0", "id": 1, "result": {"tunein:station:s74986": [{"__model__": "Image", "uri": "https://cdn-radiotime-logos.tunein.com/s74986q.png"}]}`

Get a Tidal track image:
`curl -d '{"jsonrpc":"2.0","id":1,"method":"core.library.get_images","params":{"uris":["tidal:track:19450:77660805:77660816"]}}' -H 'Content-Type: application/json' http://localhost:6680/mopidy/rpc`
Result (no image):
`{"jsonrpc": "2.0", "id": 1, "result": {"tidal:track:19450:77660805:77660816": []}}`

**Comment by fmarzocca** [comment]
Not an Iris issue

**Comment by tehkillerbee** [comment]
Agreed, I have fixed the bug now, it was related to some changes I did to the image getter functions not including individual tracks. Please test with latest master.

![image](https://github.com/tehkillerbee/mopidy-tidal/assets/815886/9c36f9da-ab39-4e14-88cc-ad6145e6a69a)

**Comment by tehkillerbee** [comment]
Fixed in https://github.com/tehkillerbee/mopidy-tidal/commit/faf9e2cd41f4a94a0f0dc2f64c23f59267b86a37

**Comment by fmarzocca** [comment]
can't do it before tomorrow. I'm out now.

**Comment by tehkillerbee** [comment]
@fmarzocca Thanks for your valuable feedback, have now updated the v0.3.6 release
