### ISSUE TITLE
Bug: Setting PKCE without setting login_server_port should not be allowed

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#158]
Setting PKCE without login_server_port as well does not make sense. Fallback to OAuth if this is the case

**Comment by GioF71** [comment]
Hello, I was thinking of asking you about this. Actually, once you have your json file, there might be no reason for opening the utility login port. I believe maybe you could raise an error if one chooses pkce auth, login port is not set, and there is no json file with the auth details. Would it be possible?

**Comment by tehkillerbee** [comment]
Indeed, the login page is only needed when a PKCE session does not exist. And it should only get spawned if this is the case - or if the session fails reloading for some reason.

Yes, we should have a check similar to the other config options where a warning is thrown and OAUTH is used as a fallback. We could also consider always using port 8989 as default, if it has not been set by the user while auth mode PKCE is used.

**Comment by GioF71** [comment]
Yes that would be the best solution I believe!

**Comment by tehkillerbee** [comment]
Fixed in v0.3.6
