### ISSUE TITLE
Fix confusing quality log messages

### ISSUE THREAD

**Issue by fmarzocca** [tehkillerbee/mopidy-tidal#163]
I was looking at the log and found these lines:

```
Mar 19 16:58:17 pab mopidy[2154]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.playback No HI_RES available for this track; Using playback quality: LOSSLESS
Mar 19 16:58:17 pab mopidy[2154]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.playback Starting playback of track:96830423, (quality:HI_RES, codec:MQA, 16bit/44100Hz)
```
The first one states quality is LOSSLESS, the second reports quality as HI_RES...
Which one is right?
I checked with `tidalapi` and it reports HI_RES for this track.

**Comment by tehkillerbee** [comment]
This message refers to the fact that you requested HI_RES audio as the tidal quality but it was not listed/available in the metadata for that track. But now that we use the stream to get the quality, we should probably use that instead.

The actual quality used for playback will always be listed in the following log message: "Starting playback of track:96830423, (quality:HI_RES, codec:MQA, 16bit/44100Hz)"

FYI, if you want lossless quality, you should use HI_RES_LOSSLESS but maybe you prefer to use  MQA instead?

**Comment by fmarzocca** [comment]
> FYI, if you want lossless quality, you should use HI_RES_LOSSLESS but maybe you prefer to use MQA instead?

I have set HI_RES_LOSSLESS in mopidy.conf.

**Comment by tehkillerbee** [comment]
Closing, as this issue does not exist when MQA has been removed.
