### ISSUE TITLE
Another Unhandled exception in TidalBackend

### ISSUE THREAD

**Issue by honza-1** [tehkillerbee/mopidy-tidal#177]
I am using mopidy 3.3.0 on raspberry pi. After updating mopidy-tidal and deleting oauth json file I run in the problem described several times under issues. 

Sep 15 20:59:25 hifi mopidy[489]: INFO     [TidalBackend-7] mopidy_tidal.backend Visit link.tidal.com/NUEXM to log in, the code will expi
Sep 15 21:04:26 hifi mopidy[489]: ERROR    [TidalBackend-7] pykka Unhandled exception in TidalBackend (urn:uuid:cb2df7c9-b076-419a-be63-1
Sep 15 21:04:26 hifi mopidy[489]: Traceback (most recent call last):
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 179, in _actor_loop
Sep 15 21:04:26 hifi mopidy[489]:     self.on_start()
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 83, in on_start
Sep 15 21:04:26 hifi mopidy[489]:     self.oauth_login_new_session(oauth_file)
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_se
Sep 15 21:04:26 hifi mopidy[489]:     self._session.login_oauth_simple(function=logger.info)
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 323, in login_oauth_simple
Sep 15 21:04:26 hifi mopidy[489]:     future.result()
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
Sep 15 21:04:26 hifi mopidy[489]:     return self.__get_result()
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
Sep 15 21:04:26 hifi mopidy[489]:     raise self._exception
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Sep 15 21:04:26 hifi mopidy[489]:     result = self.fn(*self.args, **self.kwargs)
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 355, in _process_link_login
Sep 15 21:04:26 hifi mopidy[489]:     json = self._wait_for_link_login(json)
Sep 15 21:04:26 hifi mopidy[489]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 389, in _wait_for_link_login
Sep 15 21:04:26 hifi mopidy[489]:     raise TimeoutError('You took too long to log in')
Sep 15 21:04:26 hifi mopidy[489]: TimeoutError: You took too long to log in

No oauth json file is created
I checked access permissions on mopidy data directory, which were ok. Nevertheless I changed to 777 for testing without positive result. I tried to install from master, which failed with message about missing setup.py. After installing from https://github.com/BlackLight/mopidy-tidal I did not get a better result as well.
Have I overseen a relevant information ?

Thanks for any help !

My reaction time was surely under 300 seconds.

**Comment by fmarzocca** [comment]
Maybe this?
`Sep 15 21:04:26 hifi mopidy[489]: TimeoutError: You took too long to log in`

**Comment by honza-1** [comment]
I remove mopidy-tidal and installed freshly from sudo pip3 install git+https://github.com/BlackLight/mopidy-tidal

The output  from journalctl -f -u mopidy:

Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Connecting to TIDAL.. Quality = LOSSLESS
Sep 21 21:19:46 hifi mopidy[11627]: WARNING  [TidalBackend-7] mopidy_tidal.backend Connecting to TIDAL.. always provide client_id and client_secret together
Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Connecting to TIDAL.. using default client id & client secret from python-tidal
Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Loading OAuth session from /var/lib/mopidy/tidal/tidal-oauth.json...
Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Could not load OAuth session from /var/lib/mopidy/tidal/tidal-oauth.json: Expecting value: line 1 column 1 (char 0)
Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Creating new OAuth session...
Sep 21 21:19:46 hifi mopidy[11627]: INFO     [TidalBackend-7] mopidy_tidal.backend Visit link.tidal.com/VXGGW to log in, the code will expire in 300 seconds
Sep 21 21:20:13 hifi mopidy[11627]: ERROR    [TidalBackend-7] pykka Unhandled exception in TidalBackend (urn:uuid:54393c45-f0ce-4362-bd30-09cfd73b16e6):
Sep 21 21:20:13 hifi mopidy[11627]: Traceback (most recent call last):
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 179, in _actor_loop
Sep 21 21:20:13 hifi mopidy[11627]:     self.on_start()
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 83, in on_start
Sep 21 21:20:13 hifi mopidy[11627]:     self.oauth_login_new_session(oauth_file)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_session
Sep 21 21:20:13 hifi mopidy[11627]:     self._session.login_oauth_simple(function=logger.info)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 323, in login_oauth_simple
Sep 21 21:20:13 hifi mopidy[11627]:     future.result()
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
Sep 21 21:20:13 hifi mopidy[11627]:     return self.__get_result()
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
Sep 21 21:20:13 hifi mopidy[11627]:     raise self._exception
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Sep 21 21:20:13 hifi mopidy[11627]:     result = self.fn(*self.args, **self.kwargs)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 364, in _process_link_login
Sep 21 21:20:13 hifi mopidy[11627]:     self.user = tidalapi.User(self, user_id=json['userId']).factory()
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 49, in factory
Sep 21 21:20:13 hifi mopidy[11627]:     return self.request.map_request("users/%s" % self.id, parse=self.parse)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/request.py", line 118, in map_request
Sep 21 21:20:13 hifi mopidy[11627]:     return self.map_json(json_obj, parse=parse)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/request.py", line 125, in map_json
Sep 21 21:20:13 hifi mopidy[11627]:     return parse(json_obj)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 65, in parse
Sep 21 21:20:13 hifi mopidy[11627]:     return user.parse(json_obj)
Sep 21 21:20:13 hifi mopidy[11627]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 114, in parse
Sep 21 21:20:13 hifi mopidy[11627]:     self.gender = json_obj["gender"]
Sep 21 21:20:13 hifi mopidy[11627]: KeyError: 'gender'
Sep 21 21:20:13 hifi mopidy[11627]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:54393c45-f0ce-4362-bd30-09cfd73b16e6) stopped before handling the message

There was no file created under /var/lib/mopidy/tidal/tidal-oauth.json.

For testing I created it with sudo -u mopidy touch with success and
changes permissions with chown 777

Next try of starting mopidy had the same result.

If I try to install from master sudo pip3 install git+https://github.com/thekillerbee/mopidy-tidal
I am asked for authentication, which I cannot provide on command prompt.

If I try to install from downloaded tar.gz with sudo pip3 install mopidy-tidal-0.3.6.tar.gz
I receive     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-22k_3qr3/setup.py'

Please help.

**Comment by tehkillerbee** [comment]
FYI, only the releases on PyPi or from this repository are supported. The repo from BlackLight is not up to date. 

Make sure to remove both mopidy-tidal and tidalapi before continuing. Try installing the latest mopidy-tidal from PyPi, paired with the latest tidalapi from PyPi and see if this solves the problem.  Installing mopidy-tidal from PyPi should be enough. 

> I am asked for authentication, which I cannot provide on command prompt.

What authentication are you talking about here? PKCE authentication requires you to visit a separate (local) Web page to authenticate tidal. For OAUTH, it should be adequate to visit the link for authentication to complete.

**Comment by honza-1** [comment]
Thanks for the reply !! 
Upgrading from PyPi and removing and reinstalling form PyPi was were I started. Because of the issue with unhandled ecxeption I went through the issues and tried other sources.

Anyway I started from scratch by

**Stopping the mopidy service**

**sudo pip3 uninstall mopidy-tidal**
Skipping mopidy-tidal as it is not installed.

**sudo pip3 uninstall tidal-api**
Skipping tidal-api as it is not installed.

**sudo pip3 install mopidy-tidal**
Installing collected packages: tidalapi, mopidy-tidal
Successfully installed mopidy-tidal-0.3.2 tidalapi-0.7.1
...


**sudo pip3 install --upgrade tidalapi**
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: tidalapi in /usr/local/lib/python3.7/dist-packages (0.7.1)

Starting the mopidy service

Output from journalctl -f -u mopidy

Sep 22 18:12:57 hifi mopidy[13166]: INFO     [TidalBackend-7] mopidy_tidal.backend Could not load OAuth session from /var/lib/mopidy/tidal/tidal-oauth.json: [Errno 2] No such file or directory: '/var/lib/mopidy/tidal/tidal-oauth.json'
Sep 22 18:12:57 hifi mopidy[13166]: INFO     [TidalBackend-7] mopidy_tidal.backend Creating new OAuth session...
Sep 22 18:12:57 hifi mopidy[13166]: INFO     [TidalBackend-7] mopidy_tidal.backend Visit link.tidal.com/ZWAWF to log in, the code will expire in 300 seconds

I visited the website and confirmed. journalctl continued with

Sep 22 18:13:36 hifi mopidy[13166]: ERROR    [TidalBackend-7] pykka Unhandled exception in TidalBackend (urn:uuid:fca4c3c5-a14d-4e63-8fa8-843b534c74df):
Sep 22 18:13:36 hifi mopidy[13166]: Traceback (most recent call last):
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 179, in _actor_loop
Sep 22 18:13:36 hifi mopidy[13166]:     self.on_start()
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 83, in on_start
Sep 22 18:13:36 hifi mopidy[13166]:     self.oauth_login_new_session(oauth_file)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_session
Sep 22 18:13:36 hifi mopidy[13166]:     self._session.login_oauth_simple(function=logger.info)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 323, in login_oauth_simple
Sep 22 18:13:36 hifi mopidy[13166]:     future.result()
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
Sep 22 18:13:36 hifi mopidy[13166]:     return self.__get_result()
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
Sep 22 18:13:36 hifi mopidy[13166]:     raise self._exception
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Sep 22 18:13:36 hifi mopidy[13166]:     result = self.fn(*self.args, **self.kwargs)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/session.py", line 364, in _process_link_login
Sep 22 18:13:36 hifi mopidy[13166]:     self.user = tidalapi.User(self, user_id=json['userId']).factory()
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 49, in factory
Sep 22 18:13:36 hifi mopidy[13166]:     return self.request.map_request("users/%s" % self.id, parse=self.parse)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/request.py", line 118, in map_request
Sep 22 18:13:36 hifi mopidy[13166]:     return self.map_json(json_obj, parse=parse)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/request.py", line 125, in map_json
Sep 22 18:13:36 hifi mopidy[13166]:     return parse(json_obj)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 65, in parse
Sep 22 18:13:36 hifi mopidy[13166]:     return user.parse(json_obj)
Sep 22 18:13:36 hifi mopidy[13166]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/user.py", line 114, in parse
Sep 22 18:13:36 hifi mopidy[13166]:     self.gender = json_obj["gender"]
Sep 22 18:13:36 hifi mopidy[13166]: KeyError: 'gender'
Sep 22 18:13:36 hifi mopidy[13166]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:fca4c3c5-a14d-4e63-8fa8-843b534c74df) stopped before handling the message

No file /var/lib/mopidy/tidal/tidal-oauth.json was created

ls -l /var/lib/mopidy
total 52
drwxr-xr-x  2 mopidy audio  4096 Mar 23  2020 http
drwxr-xr-x  2 mopidy audio  4096 Jul 26  2020 iris
drwxr-xr-x  3 mopidy audio  4096 May 28  2022 local
drwxr-xr-x  2 mopidy audio  4096 Jun 23  2018 local-images
drwxr-xr-x  2 mopidy audio  4096 Dec 26  2019 m3u
drwxr-xr-x 15 mopidy audio  4096 Nov 18  2019 media
drwxr-xr-x  2 mopidy audio 20480 Sep 15 12:30 playlists
drwxr-xr-x  2 mopidy audio  4096 Sep 21 21:52 tidal

The problem remains. 

Concerning the question about the authentication I apologize not to be clear.
I was talking about a prompt from git to log in whilst trying to install directly from master.

What can I try next ??

Thanks in advance.

**Comment by tehkillerbee** [comment]
```
Sep 22 18:13:36 hifi mopidy[13166]: self.gender = json_obj["gender"]
Sep 22 18:13:36 hifi mopidy[13166]: KeyError: 'gender'
```
It looks like there has been a change in the tidalapi, otherwise this should not happen. I will take a look and see if I can replicate the problem on my side.

**Comment by honza-1** [comment]
Yes, that's it. 

Thanks !

**Comment by tehkillerbee** [comment]
Ok, closing this issue (assuming it is fixed). Otherwise, feel free to reopen.

**Comment by fmarzocca** [comment]
> **sudo pip3 uninstall tidal-api**
> Skipping tidal-api as it is not installed.

You mispelled this. `tidalapi`, not `tidal-api`
