### ISSUE TITLE
Update pypi with latest release

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#18]

**Comment by srob** [comment]
This would be really good to do since the released version is not compatible with python 3.

I eventually found that cloning the repository to the local file system and then installing via pip3 got mopidy-tidal working quite nicely on my pi zero/pirate audio based mopidy installation.

**Comment by tehkillerbee** [comment]
I agree and it might scare new users away, if the mopidy-tidal plugin does not work out of the box. I will look into how to update pypi repo ASAP.
