### ISSUE TITLE
PyPi for new version?

### ISSUE THREAD

**Issue by fmarzocca** [tehkillerbee/mopidy-tidal#182]
Hi @tehkillerbee,
when will the new version be available on PyPi, with the mods for new tidalapi?

**Comment by tehkillerbee** [comment]
@fmarzocca I'm working on it, I wanted to fix the unit tests before the next mopidy-tidal release, as a lot of them are currently broken.

**Comment by fmarzocca** [comment]
Thanks!

**Comment by tehkillerbee** [comment]
Sorry for the delay, the latest version is now available on PyPi
