### ISSUE TITLE
ERROR in initialisation: "Invalid token" (kgsOOmYk3zShYrNP)

### ISSUE THREAD

**Issue by DerNuntius** [tehkillerbee/mopidy-tidal#19]
Hi,
I powered a mopidy instance up just as always but now mopidy-tidal has an invalid token.

```
{"status":401,"subStatus":6004,"userMessage":"Invalid token"}
ERROR    2020-05-13 19:00:56,197 [13520:TidalBackend-3] pykka
  Unhandled exception in TidalBackend (urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-5a4b08ae0590):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    self.on_start()
  File "/home/pi/.local/lib/python3.8/site-packages/mopidy_tidal/backend.py", line 35, in on_start
    if self._session.login(self._username, self._password):
  File "/home/pi/.local/lib/python3.8/site-packages/tidalapi/__init__.py", line 86, in login
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=xxxxxxxxxxxxxxxx
ERROR    2020-05-13 19:00:56,203 [13520:MainThread] mopidy.commands
  Actor died: TidalBackend (urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-5a4b08ae0590) stopped before handling the message
```

**Comment by tehkillerbee** [comment]
Yes, the api token is not valid anymore. This is also apparent from the python-tidal package that mopidy-tidal depends on:
https://github.com/tamland/python-tidal/issues

I have noticed that other (illegal?) tidal tools has updated their token although I am not exactly sure where this token has been obtained: hZ9wuySZCmpLLiui

**Comment by DerNuntius** [comment]
Thanks for the new token!
I updated the variable "self.api_token" and now it works.

```
~/.local/lib/python3.8/site-packages/tidalapi4mopidy/__init__.py
~/.local/lib/python3.8/site-packages/tidalapi/__init__.py
```

**Comment by DerNuntius** [comment]
I won't close the issue yet :) 
Until it's not fixed.

**Comment by DerNuntius** [comment]
Umm my instance now fetches ALAC files from the tidal server. I installed a gstreamer extention (gstreamer1.0-libav) for it but still..it's a bit weird.

**Comment by tehkillerbee** [comment]
Interesting. But in my case, I still stream M4A/AAC (I do not have a premium subscription). So I think that is unrelated.

**Comment by tehkillerbee** [comment]
python-tidal / tidalapi has now been updated with the latest token as of ver. 0.6.5. I will now close this issue
