### ISSUE TITLE
Invalid token=kgsOOmYk3zShYrNP

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#20]
Please note that the mopidy tidal player has recently been unable to authenticate:
Please let me know if the problem can be solved. Many thanks !

May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,149 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   GLib mainloop got SIGTERM. Exiting...
May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,149 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   Stopping Mopidy frontends
May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,152 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   Stopping Mopidy core
May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,154 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   Stopping Mopidy backends
May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,156 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   Stopping Mopidy audio
May 14 20:12:25 localhost mopidy[14159]: INFO     2020-05-14 20:12:25,157 [14159:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14159]:   Stopping Mopidy mixer
May 14 20:12:25 localhost mopidy[14159]: {"status":401,"subStatus":6004,"userMessage":"Invalid token"}
May 14 20:12:25 localhost systemd[1]: Stopping Mopidy music server...
May 14 20:12:25 localhost systemd[1]: mopidy.service: Succeeded.
May 14 20:12:25 localhost systemd[1]: Stopped Mopidy music server.
May 14 20:12:25 localhost systemd[1]: Starting Mopidy music server...
May 14 20:12:25 localhost systemd[1]: Started Mopidy music server.
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,512 [14303:MainThread] mopidy.__main__
May 14 20:12:25 localhost mopidy[14303]:   Starting Mopidy 3.0.2
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,526 [14303:MainThread] mopidy.config
May 14 20:12:25 localhost mopidy[14303]:   Loading config from builtin defaults
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,527 [14303:MainThread] mopidy.config
May 14 20:12:25 localhost mopidy[14303]:   Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,527 [14303:MainThread] mopidy.config
May 14 20:12:25 localhost mopidy[14303]:   Loading config from file:///etc/mopidy/mopidy.conf
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,528 [14303:MainThread] mopidy.config
May 14 20:12:25 localhost mopidy[14303]:   Loading config from command line options
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,604 [14303:MainThread] mopidy.__main__
May 14 20:12:25 localhost mopidy[14303]:   Enabled extensions: musicbox_webclient, file, http, stream, m3u, tidal, softwaremixer
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,605 [14303:MainThread] mopidy.__main__
May 14 20:12:25 localhost mopidy[14303]:   Disabled extensions: none
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,664 [14303:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14303]:   Starting Mopidy mixer: SoftwareMixer
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,666 [14303:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14303]:   Mixer volume set to 100
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,666 [14303:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14303]:   Starting Mopidy audio
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,668 [14303:MainThread] mopidy.commands
May 14 20:12:25 localhost mopidy[14303]:   Starting Mopidy backends: TidalBackend, FileBackend, M3UBackend, StreamBackend
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,673 [14303:Audio-2] mopidy.audio.actor
May 14 20:12:25 localhost mopidy[14303]:   Audio output set to "autoaudiosink"
May 14 20:12:25 localhost mopidy[14303]: INFO     2020-05-14 20:12:25,674 [14303:TidalBackend-3] mopidy_tidal.backend
May 14 20:12:25 localhost mopidy[14303]:   Connecting to TIDAL.. Quality = LOSSLESS
May 14 20:12:26 localhost mopidy[14303]: ERROR    2020-05-14 20:12:26,086 [14303:TidalBackend-3] pykka
May 14 20:12:26 localhost mopidy[14303]:   Unhandled exception in TidalBackend (urn:uuid:15e456d7-4bd1-4747-b4c6-aa9b1b34ae9f):
May 14 20:12:26 localhost mopidy[14303]: Traceback (most recent call last):
May 14 20:12:26 localhost mopidy[14303]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
May 14 20:12:26 localhost mopidy[14303]:     self.on_start()
May 14 20:12:26 localhost mopidy[14303]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Tidal-0.2.3-py3.7.egg/mopidy_tidal/backend.py", line 35, in on_start
May 14 20:12:26 localhost mopidy[14303]:     if self._session.login(self._username, self._password):
May 14 20:12:26 localhost mopidy[14303]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi-0.6.4-py3.7.egg/tidalapi/__init__.py", line 86, in login
May 14 20:12:26 localhost mopidy[14303]:     request.raise_for_status()
May 14 20:12:26 localhost mopidy[14303]:   File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
May 14 20:12:26 localhost mopidy[14303]:     raise HTTPError(http_error_msg, response=self)
May 14 20:12:26 localhost mopidy[14303]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP
May 14 20:12:26 localhost mopidy[14303]: ERROR    2020-05-14 20:12:26,091 [14303:MainThread] mopidy.commands
May 14 20:12:26 localhost mopidy[14303]:   Actor died: TidalBackend (urn:uuid:15e456d7-4bd1-4747-b4c6-aa9b1b34ae9f) stopped before handling the message
May 14 20:12:26 localhost mopidy[14303]: INFO     2020-05-14 20:12:26,091 [14303:MainThread] mopidy.commands
May 14 20:12:26 localhost mopidy[14303]:   Starting Mopidy core
May 14 20:12:26 localhost mopidy[14303]: INFO     2020-05-14 20:12:26,118 [14303:MainThread] mopidy.commands
May 14 20:12:26 localhost mopidy[14303]:   Starting Mopidy frontends: HttpFrontend
May 14 20:12:26 localhost mopidy[14303]: INFO     2020-05-14 20:12:26,119 [14303:HttpFrontend-9] mopidy.http.actor
May 14 20:12:26 localhost mopidy[14303]:   HTTP server running at [::ffff:0.0.0.0]:6680
May 14 20:12:26 localhost mopidy[14303]: INFO     2020-05-14 20:12:26,119 [14303:MainThread] mopidy.commands
May 14 20:12:26 localhost mopidy[14303]:   Starting GLib mainloop

**Comment by tehkillerbee** [comment]
Closed, duplicate issue
