### ISSUE TITLE
Album artwork is not displayed in iris, artist artwork is displayed

### ISSUE THREAD

**Issue by srob** [tehkillerbee/mopidy-tidal#23]
Album artwork is not displayed in iris, artist artwork is displayed.

This is with mopidy-tidal 0.2.3 (installed from file system), mopidy 2.3.1 installed from pirate audio installer.

**Comment by DerNuntius** [comment]
https://github.com/tamland/python-tidal/issues/38

**Comment by tehkillerbee** [comment]
@srob Thanks for letting me know about this issue. Album art is definitely broken for me as well using another web extension (mobile).

@DerNuntius Looks like a good solution. I will try to implement it ASAP

**Comment by tehkillerbee** [comment]
Fixed in latest python-tidal 0.6.7
