### ISSUE TITLE
current sample rate

### ISSUE THREAD

**Issue by prietus** [tehkillerbee/mopidy-tidal#29]
Hello, thanks for the plugin, it works very well.
I'm trying to get sample rate of playing tracks. Neither the json rpc nor logs (in debugging mode) show that info.
I ask because I wanted to know, if that's possible, what's the sample rate of tidal using quality = LOSSLESS.
Thanks in advance.

**Comment by tehkillerbee** [comment]
Mopidy-tidal relies on the tidalapi python module and unfortunately, I don't think this functionality is supported directly by tidalapi. I think this feature makes more sense to add to the tidalapi - not mopidy-tidal.
