### ISSUE TITLE
mopidy tidal "oauth" JSON file cannot be written due to permissions issue.

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#41]
HI !
i installed mopidy-tidal on debian10 according to the specs.
I specify that I am using the root user for all operations
activating "systemctl restart mopidy" in effect appears on "journalctl -u mopidy | tail -5" the invitation link for authentication, and inserting user and psw mopidy would seem to be connected successfully, instead it is not so and the file "tidal- oauth.json "is not created.
Can you give me some suggestions? Thank you
<img width="881" alt="tidal_error" src="https://user-images.githubusercontent.com/59960414/135599019-ca701438-a4f2-4011-832a-de7cd7b3d237.PNG">

<img width="581" alt="tidal_error2" src="https://user-images.githubusercontent.com/59960414/135602099-13841ed4-ba77-4605-b200-1c4222bb19f8.PNG">

**Comment by tehkillerbee** [comment]
HI @chicco64, I suspect this issue is similar to #40. 

The moment, the HOME env. variable is used as a base when generating the path to tidal-oauth.json (See https://github.com/tehkillerbee/mopidy-tidal/blob/83ad5c4363c3c578dc7c67a9ff8ac49bec212443/mopidy_tidal/backend.py#L49) 

From your error messages, it looks like this file is never created. But since you have attached logs from two different configurations, it is difficult to tell for sure. On my platform, this path corresponds to the path used in your example, in your first image that is.  Can you confirm that the same issue occurs if you run the service as user mopidy?

The mopidy documentation lists the following
https://docs.mopidy.com/_/downloads/en/latest/pdf/

```
core/data_dir
Path to base directory for persistent data files.

Mopidy and extensions will use this path to store data that cannot be be thrown away and reproduced without
some effort. Examples include Mopidy-Local’s index of your media library and Mopidy-M3U’s stored playlists.
When running Mopidy as a regular user, this should usually be $XDG_DATA_DIR/mopidy, i.e. ~/.local/
share/mopidy.
When running Mopidy as a system service, this should usually be /var/lib/mopidy
```

How did you configure your service? I usually follow this guide: https://docs.mopidy.com/en/latest/running/service/

**Comment by chicco64** [comment]
thanks for the quick reply !"

I installed mopidy as per technical manual and using systemctl enable mopidy
I am attaching again what happens when mopidy restarts after example a reboot
and the configuration file, confirm that the access credentials (user and password) must still be entered
I believe that systemctl (automatically) uses the user "mopidy"
if you need some more logs, no problem....

<img width="855" alt="tidal_error3" src="https://user-images.githubusercontent.com/59960414/135604981-8b3c455c-b070-4faa-97e6-638951e69027.PNG">

<img width="703" alt="tidal_error4" src="https://user-images.githubusercontent.com/59960414/135604998-690a6a46-75b7-4919-86d8-1602734c6689.PNG">

**Comment by chicco64** [comment]
Hi !
i still did numerous tests but i can't get it to work, can you please help me? Thank you !

**Comment by tehkillerbee** [comment]
@chicco64 I understand you are having trouble getting mopidy-tidal running but it is limited what I can do to help, when I do not experience this issue on the platforms I have tested mopidy-tidal. I might try to test it on a similar platform, if you can describe the steps that you have taken to install it, OS configuration etc.

However, from your logs shown in your latest screenshots, I can see that you do not have permission writing the json file. The python script assumes that these directories are present, so it will not attempt to create them.

I would start checking whether the `/var/lib/mopidy/` directory and its subfolder `.config` exists - and whether you have permission to edit it. If it does not exist, there must be something wrong with your mopidy configuration. 

On my platform, running `ls -al /var/lib/mopidy` reveals that the user "mopidy" has permissions to write this directory and all the subfolders. So if you are running the service as user `mopidy`, there should not be any issue.

**Comment by chicco64** [comment]
Hi !
I confirm the problem was in the authorization of the /var/lib/mopidy/.config folder
thank you so much !!!
