### ISSUE TITLE
pykka Unhandled exception in TidalBackend

### ISSUE THREAD

**Issue by jbrepogmailcom** [tehkillerbee/mopidy-tidal#42]
On Raspberry, I am getting this error in log after authentication in web:
```
Jan 10 19:02:49 tidal-pi mopidy[3489]: ERROR    [TidalBackend-6] pykka Unhandled exception in TidalBackend (urn:uuid:a3a4d7d7-8991-4cdf-ad4b-7a6eeced585f):
Jan 10 19:02:49 tidal-pi mopidy[3489]: Traceback (most recent call last):
Jan 10 19:02:49 tidal-pi mopidy[3489]:   File "/usr/local/lib/python3.9/dist-packages/pykka/_actor.py", line 179, in _actor_loop
Jan 10 19:02:49 tidal-pi mopidy[3489]:     self.on_start()
Jan 10 19:02:49 tidal-pi mopidy[3489]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/backend.py", line 68, in on_start
Jan 10 19:02:49 tidal-pi mopidy[3489]:     self.oauth_login_new_session(oauth_file)
Jan 10 19:02:49 tidal-pi mopidy[3489]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/backend.py", line 43, in oauth_login_new_session
Jan 10 19:02:49 tidal-pi mopidy[3489]:     with open(oauth_file, 'w') as outfile:
Jan 10 19:02:49 tidal-pi mopidy[3489]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mopidy/.config/tidal-oauth.json'
Jan 10 19:02:49 tidal-pi mopidy[3489]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:a3a4d7d7-8991-4cdf-ad4b-7a6eeced585f) stopped before handling the message
```

**Comment by tehkillerbee** [comment]
Hello @jbrepogmailcom ,

It looks like the issue you are experiencing is similar to #41 

Can you verify the file permissions for the directories `/var/lib/mopidy/.config/` to store the json file?
Does the directory exist? 

Please give more details on how you have installed mopidy-tidal, are you running it as a service etc.

**Comment by jbrepogmailcom** [comment]
Yes I fixed it by sudo mkdir .config and giving it 777 priviledges. But this is a very dirty solution that should be solved properly. On Raspbery I use user pi, so access to /var/lib needs sudo. I thought that running service should be able to use /var/lib, maybe the problem happened because I ran mopidy first as normal user, so it could not create .config and then later when it ran as service the .config folder was not there.

**Comment by tehkillerbee** [comment]
@jbrepogmailcom I agree, it needs to be solved properly - and there seem to be a number of situations where the json file does not get created. 

Maybe the path to the json file needs to be adapted to how the user is running mopidy? Alternatively, mopidy-tidal should fallback to saving the json file elsewhere.

**Comment by jbrepogmailcom** [comment]
There must be some standard how running services store config data. I think I can close the discussion, it has been solved (by a workaround for now).

**Comment by tehkillerbee** [comment]
@jbrepogmailcom I would say it needs to be fixed so I will leave it open for now.

**Comment by tehkillerbee** [comment]
tidal-oauth path has been changed to use mopidy data directory as default. This should ensure that the correct directory (and permissions) are always available.
