### ISSUE TITLE
mopidy-tidal only partially reproduces the Tidal music catalog

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#46]
HI !
After the changes introduced yesterday, mopidy-tidal cannot fully reproduce the Tidal music catalog.

For example, the well-known song "u2 - the Joshua Tree // With or Without" does not play, this is the error

'# journalctl -u mopidy | tail -5'

Jan 20 08:42:15 test-c mopidy[993]:   File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
Jan 20 08:42:15 test-c mopidy[993]:     raise HTTPError(http_error_msg, response=self)
Jan 20 08:42:15 test-c mopidy[993]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/tracks/1218917/streamUrl?sessionId=36ac749a-d8d2-4caa-9cdb-c1d42c54d316&countryCode=GB&limit=999&soundQuality=LOSSLESS
Jan 20 08:42:15 test-c mopidy[993]: WARNING  [Core-5] mopidy.core.tracklist Track is not playable: tidal:track:17123:1218916:1218917
Jan 20 08:42:15 test-c mopidy[993]: INFO     [Core-5] mopidy.core.playback No playable track in the lis

Mopidy-tidal is set up with a "Tidal HIFI Plus" subscription; I also add that it works only partially in "LOSSLESS" mode while it no longer works for any songs in "LOW" mode (before the modification it worked perfectly).

Probably, client_id, client_secret are incorrect.

I trust in solving the problem.
Thank you very much

**Comment by tehkillerbee** [comment]
@chicco64 Are you still using your own key or are you using the one provided by tidalapi 0.6.9? I tested with HIGH/LOW and the key included with tidalapi and it works fine. Unfortunately, I do not have LOSSLESS mode to test.

**Comment by chicco64** [comment]
many thanks, i think i have identified the correct codes.
client_id=8SEZ.......U5Y
client_secret=owUY.....bq60=
if you can confirm that they are the right ones
now works !

**Comment by Glog78** [comment]
@chicco64 you don't need to set client_id & client_secret as long as you have the lates tidalapi. It's purely optional to set them and i would highly advice only to set them if for some reason you don't want to use the one from tidalapi

**Comment by chicco64** [comment]
Hi !
if I don't insert client_id & client_secret the player doesn't authenticate and doesn't work.
I have to enter the codes that I indicated previously
my installation is performed in October 2021
How can I install the new version of tidalapi, if you advise me to do so?
...without having to run the entire installation again...
thank you

**Comment by tehkillerbee** [comment]
@chicco64 `pip install --upgrade --force-reinstall tidalapi` should do the trick

But when updating mopidy-tidal, it should also prompt you to install the latest tidalapi, i.e. version 0.6.9

**Comment by chicco64** [comment]
yes perfect now works without entering codes
Many thanks !!!!
