### ISSUE TITLE
Tracks break after around 4 Minutes of Playback

### ISSUE THREAD

**Issue by Glog78** [tehkillerbee/mopidy-tidal#52]
Since the last tidal api update somehow my tracks don't playout but stop playing after around 4 minutes. I checked if there is some other issue with the podcast plugin, but this works fine. Any idea what that could be ?

**Comment by tehkillerbee** [comment]
@Glog78 I have not experienced this issue after upgrading. Can you send your mopidy log?

**Comment by Glog78** [comment]
![Screenshot_20220214_084634](https://user-images.githubusercontent.com/7598856/153821675-a2a9d84b-fae2-437a-bb8d-ebbed69806a3.png)
[mopidy.log](https://github.com/tehkillerbee/mopidy-tidal/files/8058818/mopidy.log)

There are 2 screenshots. One shows when it hangs. and the second is the log

**Comment by tehkillerbee** [comment]
Interesting. I have not tested with LOSSLESS; as I do not have a subscription for it.

**Comment by tehkillerbee** [comment]
@Glog78 Fortunately, I have just gotten access to HIFI/Lossless through my my ISP. I will test this issue and get back to you.

**Comment by Glog78** [comment]
One more hint ... it happens for mp3 too ... you just need to find a very long one 
![image](https://user-images.githubusercontent.com/7598856/154125245-cef3adb4-fca2-4dea-bd96-a6a902850fe3.png)

**Comment by Glog78** [comment]
thats a good question it happened to me all the time , but let me check the current state

**Comment by Glog78** [comment]
I was to early damm it ...
![image](https://user-images.githubusercontent.com/7598856/155965528-3ff77800-5f57-42f0-8b9c-30bfd07b88ed.png)

**Comment by Glog78** [comment]
![image](https://user-images.githubusercontent.com/7598856/155966883-0c2dea6e-12b7-4eb1-8e59-0f7215ef6b1f.png)
same for mpc

**Comment by tehkillerbee** [comment]
I have not been able to replicate this issue.

You seem to get many MPD connections during a relatively short time. What client are you using?

**Comment by Glog78** [comment]
oh that was just a watch -n mpc status. ;) Nothing to worry about. Had the tail running on the other side. Wanted to check if it happens with another client too, so i used mpc (mpd default).

**Comment by tehkillerbee** [comment]
Closing this issue, as there has been no further updates and the issue cannot be replicated on my side.
