### ISSUE TITLE
A maximum of 999 items is loaded in a playlist

### ISSUE THREAD

**Issue by BlackLight** [tehkillerbee/mopidy-tidal#56]
When loading a large playlist, a maximum of 999 items is loaded, no matter its size.

I suppose that 999 is a hard upper limit imposed on the API - but if that's the case mopidy-tidal should at least perform multiple requests to properly manage pagination.

**Comment by BlackLight** [comment]
After a bit of investigation, it turns out that [999 is a hard limit on `tidalapi` itself](https://github.com/tamland/python-tidal/blob/251ed480cb8ba33eeec16436593e409c49540122/tidalapi/__init__.py#L117).

I'll close this issue and open one on the `tidalapi` repo to support collections with more than 999 items.

**Comment by BlackLight** [comment]
FYI, I have [opened a PR](https://github.com/tamland/python-tidal/pull/99) on `tidalapi` to retrieve all the items instead of the first 999. I can now load my large playlists, even though it takes really long (we really need better caching: https://github.com/tehkillerbee/mopidy-tidal/issues/57, if no one is working on this I could put together a PR in the upcoming days).

The problem is that the maintainer of `tidalapi` has been keeping us on hold for almost two years for a new release and he's not accepting PRs in the meantime. So those who are facing the hard ceiling when loading playlists or other collections can use my fork in the meantime.

**Comment by tehkillerbee** [comment]
@BlackLight I agree, it is problematic that we do not know the future of `tidalapi` - and when PRs are not processed, it is difficult to do much more other than forking it. I have also been looking around for alternatives to tidalapi, other than forking/rewriting it altogether, and [pyopentidal](https://github.com/Fokka-Engineering/pyopenTIDAL) could be a possibility.

Getting in touch with the developer of `tidalapi` is a great idea and I hope he will be open to more maintainers - I would also be glad to help, as `tidalapi` is the backbone of this plugin - without it, `mopidy-tidal` is no more.
