### ISSUE TITLE
Some releases available on tidal not showing up when searching

### ISSUE THREAD

**Issue by ezanatta** [tehkillerbee/mopidy-tidal#65]
I'm using mopidy with ncmpcpp. When I search for some releases I know are available on Tidal, for some reason they do not show up within the ncmpcpp search. For example, the album "Fatale" by "Pedestrian Deposit" ([which is available on tidal](https://tidal.com/browse/album/68564981)) does not show up when searching by artist or album name. Instead, only songs from three other albums appear: "Dyer's Hands", "Austere" and "Nostalgia: 2000-06". 

Any idea why? 

By the way, thanks for the extension, has been really useful for me.

**Comment by tehkillerbee** [comment]
I just checked myself. It seems when selecting the album "Fatale" in Tidal web player, using your link, it can be displayed but cannot play. Instead an error is shown "None of the tracks added are available for streaming"

The album is not displayed when searching using the app (for me).  It is also not shown in mopidy-tidal clients.
I guess tidal web does not list albums in the search results, if they are not playable. 
FYI, mopidy-tidal and tidalapi does not populate unavailable songs/albums and a 404 error is given instead when browsing these albums.

**Comment by ezanatta** [comment]
Oh, I see then, that's something weird on tidal then. Thanks for the clarification.
