### ISSUE TITLE
Switch to pyopenTIDAL

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#66]
Due to the state of the [python-tidal](https://github.com/tamland/python-tidal) project, it might be a good idea to switch to the only alternative I can find; [pyopenTIDAL](https://github.com/Fokka-Engineering/pyopenTIDAL). This will require some rewriting of the existing Mopidy-Tidal code and also pyopenTIDAL should be rewritten into pure C to allow packaging it as a PyPi package.

**Comment by BlackLight** [comment]
With the maintainer of python-tidal confirming that the 0.7.x is just awaiting for documentation and a final wrap up, I think that I could put together a PR that targets python-tidal 0.7.x instead. An alternative like pyopenTIDAL requires a lot of work to integrate from scratch, and IMHO it's worth considering only if python-tidal is really in such an unmaintained/unusable state that we have no alternatives.

**Comment by tehkillerbee** [comment]
@BlackLight Agreed, lets close this issue for now.
