### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by nawordar** [tehkillerbee/mopidy-tidal#81]
The package on PyPi is on version 0.2.7, while the newest release is 0.3.0.

**Comment by nawordar** [comment]
Sorry for my lack of patience, but I saw that 0.2.8 was not published and I was afraid that PyPi has been forgotten :smile:

**Comment by tehkillerbee** [comment]
@nawordar No problem, PyPi has not been forgotten but there has been a lot of development lately and I wanted to get all the recent changes merged in before updating PyPi package. I plan to update it today or tomorrow.

**Comment by tehkillerbee** [comment]
Closing, as PyPi is now updated
