### ISSUE TITLE
Make cached playlist expiry time on lookup configurable

### ISSUE THREAD

**Issue by BlackLight** [tehkillerbee/mopidy-tidal#91]
The [current playlist lookup/refresh logic](https://github.com/tehkillerbee/mopidy-tidal/blob/master/mopidy_tidal/playlists.py#L242) uses a cached playlist snapshot for 5 minutes.

If a `lookup` is done within that time, then the cached snapshot will be used. Otherwise, the playlist will be refreshed from upstream.

This can be a reasonable trade-off between responsiveness of the UI vs. responsiveness of the application to external changes, but it's not always the best trade-off for everyone. Some users may not modify playlists externally so often, and hence the overhead of the upstream fetch is mostly unneeded. Some instead may want the application to have a high responsiveness to playlist changes, even if that means sacrificing a bit more time on lookup.

We probably shouldn't make assumptions about the trade-off, so this value should be configurable. The default value should probably be zero, i.e. don't refresh a playlist after the first lookup unless the application is restarted (this is a behaviour similar to that of `mopidy-spotify`).

**Comment by tehkillerbee** [comment]
Good idea, this has now been merged. Marking as closed
