### ISSUE TITLE
Can't find OAuth Flow login link 

### ISSUE THREAD

**Issue by bucadoX** [tehkillerbee/mopidy-tidal#95]
I guess I miss sth fundamental, but I don't know what: After installing Mopidy Tidal and adpating the configuration file as described I restart Mopidy and watch the log files coming in via journalctl. No matter how often I restart, there's nothing coming up offering me a login link.

**Comment by tehkillerbee** [comment]
Its likely, that Mopidy-Tidal has been installed in the wrong Python env. Is the Tidal plugin detected during Mopidy startup? If not, you should make sure you have installed it under the same python environment used by your Mopidy main installation. Can you elaborate how you have installed it?

**Comment by bucadoX** [comment]
I think somewhere there's the issue. I just noticed that I have two mopidy.conf files: one in /etc and one in ./config
I assumed a /ect install, so only modified that file. 
Anyways, there's no sign of tidal when I start up mopidy, so that's clearly the issue for the missung link entry. I'll figure it out from here I guess, so many thanls for the response at lightspeed.

**Comment by tehkillerbee** [comment]
@bucadoX Often it is a case of installing with or without sudo; in my case I install using sudo pip3 when installing Mopidy-Tidal in my "main" python virtual environment. Then I add the Tidal config to the respective Mopidy config file. I think the install guide is a bit vague in this aspect, as it assumes the user knows which python virtual environment to use for the install.

**Comment by bucadoX** [comment]
You nailed it: sudo it was. Now all tidal entries are visible in the log files including the link. Thanks again!

**Comment by tehkillerbee** [comment]
@bucadoX Great, marking this issue as closed :)
